name: 'Walk with purpose '
favicon: null
layout_spectrum: 0.1857806
typography_spectrum: 0.5138258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a4a4a'
    - '#cc0000'
    - '#161500'
    - '#ffffff'
    - '#afafaf'
  brandStrength: 1
  lightness: 0.6121868
  saturation: 0.7765503
  rhythmicContrast: 0.05370933
purpose: []
