layout_spectrum: 0.1857806
typography_spectrum: 0.5138258
color:
  saturation: 0.7765503
  lightness: 0.6121868
  brandStrength: 0.9786327
  rhythmicContrast: 0.05370933
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: 'Walk with purpose '
